const MODERN_INDIAN_STARS = [
  ['Virat Kohli', 86],
  ['Rohit Sharma', 84],
  ['Jasprit Bumrah', 88],
  ['Rishabh Pant', 85],
  ['Ravindra Jadeja', 87],
  ['Hardik Pandya', 81],
  ['Suryakumar Yadav', 83],
  ['Shubman Gill', 83],
  ['KL Rahul', 82],
  ['Yashasvi Jaiswal', 82],
  ['Ruturaj Gaikwad', 81],
  ['Sanju Samson', 81],
  ['Axar Patel', 80],
  ['Kuldeep Yadav', 81],
  ['Arshdeep Singh', 79],
  ['Mohammed Siraj', 79],
  ['Mohammed Shami', 81],
  ['Ravichandran Ashwin', 84],
  ['Yuzvendra Chahal', 79],
  ['Varun Chakravarthy', 78],
  ['Washington Sundar', 77],
  ['Ravi Bishnoi', 77],
  ['Shreyas Iyer', 80],
  ['Ishan Kishan', 79],
  ['Tilak Varma', 79],
  ['Rinku Singh', 79],
  ['Shivam Dube', 78],
  ['Nitish Kumar Reddy', 77],
  ['Abhishek Sharma', 78],
  ['Dhruv Jurel', 76],
  ['Jitesh Sharma', 75],
  ['Prasidh Krishna', 75],
  ['Avesh Khan', 75],
  ['Khaleel Ahmed', 74],
  ['T Natarajan', 78],
  ['Bhuvneshwar Kumar', 77],
  ['Deepak Chahar', 76],
  ['Shardul Thakur', 75],
  ['Rahul Chahar', 74],
  ['Mukesh Kumar', 73],
  ['Harshit Rana', 75],
  ['Mayank Yadav', 76],
  ['Mohsin Khan', 74],
  ['Yash Dayal', 73],
  ['Sai Sudharsan', 78],
  ['Rajat Patidar', 77],
  ['Devdutt Padikkal', 74],
  ['Riyan Parag', 77],
  ['Nitish Rana', 77],
  ['Rahul Tewatia', 74],
  ['Abdul Samad', 73],
  ['Nehal Wadhera', 73],
  ['Ramandeep Singh', 72],
  ['Prabhsimran Singh', 74],
  ['Shashank Singh', 74],
  ['Ashutosh Sharma', 73],
  ['Sameer Rizvi', 72],
  ['Angkrish Raghuvanshi', 71],
  ['Anuj Rawat', 71],
  ['KS Bharat', 70],
  ['Swapnil Singh', 70],
  ['Sai Kishore', 74],
  ['Vijay Shankar', 72],
  ['Abhinav Manohar', 71],
  ['Shahbaz Ahmed', 71],
  ['Amit Mishra', 72],
  ['Manish Pandey', 72],
  ['Rahul Tripathi', 74],
  ['Krunal Pandya', 76],
  ['Harpreet Brar', 72],
  ['Akash Deep', 73],
  ['Sandeep Sharma', 74],
  ['Mohit Sharma', 74],
  ['Yash Thakur', 71],
  ['Venkatesh Iyer', 77],
  ['Ajinkya Rahane', 75],
  ['Tushar Deshpande', 72],
  ['R Sai Kishore', 74],
  ['Kumar Kartikeya', 70],
  ['Hrithik Shokeen', 70],
  ['Naman Dhir', 71],
  ['Vishnu Vinod', 69],
  ['Suyash Sharma', 71],
  ['Vidwath Kaverappa', 70],
  ['Kartik Tyagi', 71],
  ['Raj Bawa', 70],
  ['Nishant Sindhu', 69],
  ['Arshin Kulkarni', 69],
  ['Kumar Kushagra', 68],
  ['Anmolpreet Singh', 69],
  ['Ayush Badoni', 72],
  ['Lalit Yadav', 70],
  ['Atharva Taide', 70],
  ['Sarfaraz Khan', 75],
  ['Priyansh Arya', 69],
  ['Vaibhav Suryavanshi', 67],
  ['Abishek Porel', 72],
  ['Rasikh Dar', 69],
  ['Aman Khan', 68],
  ['Shubham Dubey', 69],
  ['Mandeep Singh', 69],
  ['Umesh Yadav', 73],
  ['Ishant Sharma', 72],
  ['Piyush Chawla', 72],
]

const MODERN_OVERSEAS_STARS = [
  ['Pat Cummins', 92],
  ['Ben Stokes', 91],
  ['Steve Smith', 90],
  ['Joe Root', 90],
  ['Mitchell Starc', 88],
  ['Kane Williamson', 88],
  ['Babar Azam', 87],
  ['Josh Hazlewood', 86],
  ['James Anderson', 86],
  ['Shaheen Shah Afridi', 85],
  ['Marnus Labuschagne', 85],
  ['Trent Boult', 84],
  ['Travis Head', 84],
  ['Rashid Khan', 84],
  ['David Warner', 83],
  ['Jonny Bairstow', 83],
  ['Jos Buttler', 83],
  ['Phil Salt', 81],
  ['Harry Brook', 82],
  ['Liam Livingstone', 80],
  ['Sam Curran', 79],
  ['Moeen Ali', 78],
  ['Jofra Archer', 79],
  ['Mark Wood', 79],
  ['Reece Topley', 76],
  ['Gus Atkinson', 77],
  ['Ben Duckett', 79],
  ['Will Jacks', 78],
  ['Jamie Overton', 75],
  ['Brydon Carse', 75],
  ['Adil Rashid', 80],
  ['Chris Woakes', 78],
  ['Tom Banton', 74],
  ['Alex Hales', 76],
  ['Dawid Malan', 76],
  ['Sam Billings', 74],
  ['Zak Crawley', 74],
  ['Tom Curran', 75],
  ['Matthew Short', 78],
  ['Glenn Maxwell', 82],
  ['Marcus Stoinis', 79],
  ['Mitchell Marsh', 80],
  ['Cameron Green', 82],
  ['Adam Zampa', 79],
  ['Alex Carey', 77],
  ['Josh Inglis', 78],
  ['Tim David', 78],
  ['Jake Fraser-McGurk', 78],
  ['Nathan Ellis', 76],
  ['Spencer Johnson', 74],
  ['Sean Abbott', 75],
  ['Ashton Agar', 74],
  ['Matt Renshaw', 73],
  ['Aaron Hardie', 75],
  ['Tim Seifert', 74],
  ['Devon Conway', 81],
  ['Rachin Ravindra', 80],
  ['Daryl Mitchell', 80],
  ['Glenn Phillips', 79],
  ['Mitchell Santner', 78],
  ['Lockie Ferguson', 77],
  ['Matt Henry', 78],
  ['Will Young', 75],
  ['Finn Allen', 76],
  ['Michael Bracewell', 76],
  ['Mark Chapman', 74],
  ['Ish Sodhi', 74],
  ['Tim Southee', 77],
  ['Tom Latham', 77],
  ['Kusal Mendis', 77],
  ['Pathum Nissanka', 77],
  ['Charith Asalanka', 77],
  ['Wanindu Hasaranga', 80],
  ['Maheesh Theekshana', 77],
  ['Matheesha Pathirana', 79],
  ['Dilshan Madushanka', 75],
  ['Kamindu Mendis', 76],
  ['Dhananjaya de Silva', 77],
  ['Dasun Shanaka', 75],
  ['Nuwan Thushara', 74],
  ['Kagiso Rabada', 82],
  ['Heinrich Klaasen', 82],
  ['David Miller', 80],
  ['Aiden Markram', 79],
  ['Quinton de Kock', 80],
  ['Tristan Stubbs', 78],
  ['Marco Jansen', 78],
  ['Anrich Nortje', 78],
  ['Gerald Coetzee', 77],
  ['Keshav Maharaj', 77],
  ['Lungi Ngidi', 75],
  ['Ryan Rickelton', 76],
  ['Reeza Hendricks', 75],
  ['Donovan Ferreira', 74],
  ['Tabraiz Shamsi', 75],
  ['Tony de Zorzi', 73],
  ['Nicholas Pooran', 82],
  ['Sunil Narine', 81],
  ['Andre Russell', 81],
  ['Shimron Hetmyer', 79],
  ['Jason Holder', 78],
  ['Alzarri Joseph', 77],
  ['Shai Hope', 78],
  ['Brandon King', 77],
  ['Rovman Powell', 77],
  ['Romario Shepherd', 75],
  ['Sherfane Rutherford', 75],
  ['Akeal Hosein', 76],
  ['Gudakesh Motie', 74],
  ['Johnson Charles', 74],
  ['Kyle Mayers', 76],
  ['Roston Chase', 74],
  ['Shamar Joseph', 75],
  ['Babar Hayat', 69],
  ['Mohammad Rizwan', 82],
  ['Fakhar Zaman', 78],
  ['Naseem Shah', 78],
  ['Haris Rauf', 78],
  ['Shadab Khan', 78],
  ['Saim Ayub', 77],
  ['Iftikhar Ahmed', 75],
  ['Imad Wasim', 75],
  ['Mohammad Amir', 76],
  ['Hasan Ali', 74],
  ['Abrar Ahmed', 74],
  ['Usama Mir', 73],
  ['Azam Khan', 73],
  ['Salman Ali Agha', 76],
  ['Abdullah Shafique', 75],
  ['Mohammad Haris', 73],
  ['Sahibzada Farhan', 72],
  ['Rahmanullah Gurbaz', 79],
  ['Azmatullah Omarzai', 78],
  ['Mohammad Nabi', 78],
  ['Noor Ahmad', 77],
  ['Mujeeb Ur Rahman', 77],
  ['Naveen-ul-Haq', 76],
  ['Fazalhaq Farooqi', 76],
  ['Ibrahim Zadran', 76],
  ['Najibullah Zadran', 74],
  ['Gulbadin Naib', 74],
  ['Litton Das', 76],
  ['Mustafizur Rahman', 77],
  ['Shakib Al Hasan', 79],
  ['Taskin Ahmed', 76],
  ['Mehidy Hasan Miraz', 77],
  ['Towhid Hridoy', 74],
  ['Shoriful Islam', 73],
  ['Tanzid Hasan', 72],
  ['Rishad Hossain', 72],
  ['Najmul Hossain Shanto', 74],
  ['Paul Stirling', 75],
  ['Josh Little', 75],
  ['Harry Tector', 75],
  ['Lorcan Tucker', 74],
  ['Curtis Campher', 74],
  ['Mark Adair', 74],
  ['Sikandar Raza', 78],
  ['Sean Williams', 75],
  ['Blessing Muzarabani', 74],
  ['Richard Ngarava', 72],
  ['Assad Vala', 69],
  ['Gerhard Erasmus', 73],
  ['David Wiese', 74],
  ['Logan van Beek', 72],
  ['Bas de Leede', 73],
  ['Scott Edwards', 73],
  ['Roelof van der Merwe', 71],
  ['Monank Patel', 71],
  ['Ali Khan', 72],
]

const INDIAN_LEGENDS = [
  ['Sachin Tendulkar', 91],
  ['MS Dhoni', 90],
  ['Virender Sehwag', 88],
  ['Rahul Dravid', 89],
  ['Sourav Ganguly', 87],
  ['VVS Laxman', 86],
  ['Yuvraj Singh', 88],
  ['Suresh Raina', 85],
  ['Gautam Gambhir', 84],
  ['Robin Uthappa', 81],
  ['Dinesh Karthik', 80],
  ['Irfan Pathan', 84],
  ['Yusuf Pathan', 83],
  ['Harbhajan Singh', 85],
  ['Anil Kumble', 89],
  ['Zaheer Khan', 86],
  ['Javagal Srinath', 85],
  ['Kapil Dev', 90],
  ['Sunil Gavaskar', 89],
  ['Mohammad Azharuddin', 84],
  ['Ajay Jadeja', 81],
  ['Robin Singh', 81],
  ['Naman Ojha', 77],
  ['Ashish Nehra', 82],
  ['Praveen Kumar', 80],
  ['Munaf Patel', 77],
  ['RP Singh', 79],
  ['Murali Vijay', 80],
  ['Parthiv Patel', 78],
  ['Amit Bhandari', 74],
  ['S Badrinath', 77],
  ['Ambati Rayudu', 81],
  ['Pragyan Ojha', 79],
  ['Manoj Tiwary', 76],
  ['Pawan Negi', 73],
]

const GLOBAL_LEGENDS = [
  ['AB de Villiers', 91],
  ['Chris Gayle', 90],
  ['Lasith Malinga', 89],
  ['Shane Watson', 88],
  ['Kieron Pollard', 87],
  ['Dale Steyn', 89],
  ['Hashim Amla', 88],
  ['Jacques Kallis', 91],
  ['Graeme Smith', 86],
  ['Shaun Pollock', 88],
  ['Makhaya Ntini', 84],
  ['Jonty Rhodes', 85],
  ['Faf du Plessis', 84],
  ['Ricky Ponting', 91],
  ['Adam Gilchrist', 90],
  ['Michael Hussey', 87],
  ['Brett Lee', 88],
  ['Shane Warne', 92],
  ['Glenn McGrath', 91],
  ['Matthew Hayden', 88],
  ['Andrew Symonds', 87],
  ['Michael Clarke', 87],
  ['Brad Haddin', 82],
  ['Mitchell Johnson', 86],
  ['Nathan Bracken', 81],
  ['Kevin Pietersen', 88],
  ['Andrew Flintoff', 87],
  ['Alastair Cook', 87],
  ['Stuart Broad', 86],
  ['Graeme Swann', 84],
  ['Ian Bell', 83],
  ['Eoin Morgan', 84],
  ['Jonathan Trott', 82],
  ['Ravi Bopara', 79],
  ['James Vince', 77],
  ['Shahid Afridi', 88],
  ['Shoaib Akhtar', 88],
  ['Saeed Anwar', 87],
  ['Inzamam-ul-Haq', 88],
  ['Younis Khan', 87],
  ['Misbah-ul-Haq', 84],
  ['Abdul Razzaq', 83],
  ['Wasim Akram', 92],
  ['Waqar Younis', 90],
  ['Saqlain Mushtaq', 85],
  ['Mohammad Yousuf', 86],
  ['Umar Gul', 82],
  ['Kumar Sangakkara', 91],
  ['Mahela Jayawardene', 89],
  ['Sanath Jayasuriya', 89],
  ['Muttiah Muralitharan', 92],
  ['Chaminda Vaas', 87],
  ['Tillakaratne Dilshan', 86],
  ['Thisara Perera', 82],
  ['Nuwan Kulasekara', 80],
  ['Brendon McCullum', 89],
  ['Ross Taylor', 87],
  ['Daniel Vettori', 86],
  ['Stephen Fleming', 85],
  ['Shane Bond', 86],
  ['Jacob Oram', 82],
  ['Scott Styris', 80],
  ['Chris Cairns', 85],
  ['Brian Lara', 92],
  ['Dwayne Bravo', 86],
  ['Shivnarine Chanderpaul', 86],
  ['Curtly Ambrose', 90],
  ['Courtney Walsh', 89],
  ['Ramnaresh Sarwan', 82],
  ['Dwayne Smith', 81],
  ['Marlon Samuels', 82],
  ['Tamim Iqbal', 82],
  ['Mashrafe Mortaza', 81],
  ['Mushfiqur Rahim', 81],
  ['Mohammad Ashraful', 78],
]

export const MARQUEE_PLAYERS = new Set([
  'Virat Kohli',
  'MS Dhoni',
  'Rohit Sharma',
  'Jasprit Bumrah',
  'Rishabh Pant',
  'Hardik Pandya',
  'Suryakumar Yadav',
  'Shubman Gill',
  'Pat Cummins',
  'Ben Stokes',
  'Steve Smith',
  'Joe Root',
  'Kane Williamson',
  'Babar Azam',
  'Rashid Khan',
  'Sachin Tendulkar',
  'AB de Villiers',
  'Chris Gayle',
  'Shane Warne',
  'Muttiah Muralitharan',
  'Wasim Akram',
  'Brian Lara',
  'Jacques Kallis',
  'Ricky Ponting',
  'Kumar Sangakkara',
  'Lasith Malinga',
])

export const CRICKET_ROSTER = [
  ...MODERN_INDIAN_STARS,
  ...MODERN_OVERSEAS_STARS,
  ...INDIAN_LEGENDS,
  ...GLOBAL_LEGENDS,
]
